import type { NextPage } from "next";
import { useState } from "react";
import FlexDrag from "./flex-drag";
import GridDrag from "./grid-flex";
import style from "../styles/home.module.css";
import Head from "next/head";

const Home: NextPage = () => {
  const [section, setSection] = useState<"grid" | "flex">("grid");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={style.gridContaoner}>
          <div
            data-active={section === "grid"}
            className={style.item}
            onClick={() => setSection("grid")}
          >
            Grid Based
          </div>
          <div
            data-active={section === "flex"}
            className={style.item}
            onClick={() => setSection("flex")}
          >
            Flex Based
          </div>
        </div>
        <div className={style.content}>
          {section === "grid" ? <GridDrag /> : <FlexDrag />}
        </div>
      </main>
    </>
  );
};

export default Home;
